FROM python:3.12-slim

WORKDIR /app

COPY docker/requirements.txt .

# declare an arg
ARG DISABLE_SSL_FOR_PIP

# If this arg is set to 1, then disable the SSL check. Mainly for Xin
RUN \
    if [ "${DISABLE_SSL_FOR_PIP}" = "1" ] ; \
        then echo "Disabling SSL checks for pip" ; \
        pip config set global.trusted-host "pypi.org files.pythonhosted.org pypi.python.org" && pip config set global.timeout 900 ; \
    fi \ 
    && pip install -r requirements.txt

COPY . .